'use strict';

/**
 * Kasbah CLI Shim — wraps every detected AI CLI with a governed shim.
 *
 * For each detected CLI (claude, ollama, aider, codex, gh copilot, llm, …)
 * we write a shim script to ~/.kasbah/shims/<name> that:
 *   1. Records the invocation (timestamp, args, cwd, parent process) to the audit chain
 *   2. Pre-flight scans args that look like prompts
 *   3. Sets HTTPS_PROXY so all provider calls route through Kasbah
 *   4. Execs the real binary with the same args
 *   5. Streams stdout/stderr back unchanged
 *
 * Activation: user runs `eval "$(curl -s http://127.0.0.1:8788/v1/shim/init)"`
 * which prepends ~/.kasbah/shims to PATH.
 *
 *   GET  /v1/shim/init                — shell snippet to source
 *   GET  /v1/shim/list                — which CLIs have shims
 *   POST /v1/shim/install             — write shims for all detected CLIs
 *   POST /v1/shim/uninstall           — remove all shims
 *   GET  /v1/shim/recent              — last 50 governed CLI invocations
 */

const fs   = require('fs');
const path = require('path');
const os   = require('os');
const http = require('http');

const SHIM_DIR  = path.join(os.homedir(), '.kasbah', 'shims');
const LOG_FILE  = path.join(os.homedir(), '.kasbah', 'cli-invocations.jsonl');

// Catalog of every AI CLI we know how to govern.
// Each entry: bin name, type, prompt-arg heuristic, real-binary lookup.
const AI_CLI_CATALOG = [
  // ── Frontier coding agents ──
  { bin: 'claude',        kind: 'frontier-agent', label: 'Claude Code'           },
  { bin: 'codex',         kind: 'frontier-agent', label: 'OpenAI Codex CLI'       },
  { bin: 'cursor-agent',  kind: 'frontier-agent', label: 'Cursor Agent'           },
  { bin: 'cline',         kind: 'frontier-agent', label: 'Cline'                  },
  { bin: 'continue',      kind: 'frontier-agent', label: 'Continue'               },
  { bin: 'cody',          kind: 'frontier-agent', label: 'Sourcegraph Cody'       },
  { bin: 'tabby',         kind: 'frontier-agent', label: 'Tabby'                  },
  { bin: 'aider',         kind: 'frontier-agent', label: 'Aider'                  },
  { bin: 'sweep',         kind: 'frontier-agent', label: 'Sweep'                  },
  { bin: 'devin',         kind: 'frontier-agent', label: 'Devin (Cognition)'      },
  { bin: 'gpt-engineer',  kind: 'frontier-agent', label: 'GPT Engineer'           },
  { bin: 'metagpt',       kind: 'frontier-agent', label: 'MetaGPT'                },
  { bin: 'autogpt',       kind: 'frontier-agent', label: 'AutoGPT'                },
  { bin: 'crewai',        kind: 'frontier-agent', label: 'CrewAI'                 },
  { bin: 'interpreter',   kind: 'frontier-agent', label: 'Open Interpreter'       },
  { bin: 'goose',         kind: 'frontier-agent', label: 'Goose (Block)'          },
  // ── Generic AI CLIs ──
  { bin: 'ollama',        kind: 'llm-runtime',   label: 'Ollama'                  },
  { bin: 'lms',           kind: 'llm-runtime',   label: 'LM Studio CLI'           },
  { bin: 'llm',           kind: 'chat-cli',      label: 'llm (Simon Willison)'    },
  { bin: 'aichat',        kind: 'chat-cli',      label: 'AIChat'                  },
  { bin: 'mods',          kind: 'chat-cli',      label: 'Charm Mods'              },
  { bin: 'chatgpt',       kind: 'chat-cli',      label: 'chatgpt CLI'             },
  { bin: 'gpt',           kind: 'chat-cli',      label: 'gpt CLI'                 },
  { bin: 'chatblade',     kind: 'chat-cli',      label: 'Chatblade'               },
  { bin: 'shell-genie',   kind: 'chat-cli',      label: 'Shell-Genie'             },
  { bin: 'smartcat',      kind: 'chat-cli',      label: 'SmartCat'                },
  // ── Provider clients ──
  { bin: 'openai',        kind: 'provider-cli',  label: 'OpenAI CLI'              },
  { bin: 'anthropic',     kind: 'provider-cli',  label: 'Anthropic CLI'           },
  { bin: 'replicate',     kind: 'provider-cli',  label: 'Replicate CLI'           },
  { bin: 'huggingface-cli', kind:'provider-cli', label: 'HuggingFace CLI'         },
  // ── IDE assistants ──
  { bin: 'gh',            kind: 'ide-assist',    label: 'GitHub CLI (Copilot)',   subcommand: 'copilot' },
  // ── Local model runners ──
  { bin: 'llama-server',  kind: 'llm-runtime',   label: 'llama.cpp server'        },
  { bin: 'mlx_lm',        kind: 'llm-runtime',   label: 'Apple MLX'               },
  { bin: 'vllm',          kind: 'llm-runtime',   label: 'vLLM'                    },
];

const SHIM_TEMPLATE = (binName, realPath, apiUrl, proxyUrl) => `#!/usr/bin/env bash
# Kasbah-governed shim for ${binName}
# Real binary: ${realPath}
# Generated: ${new Date().toISOString()}
# Do not edit — regenerated by /v1/shim/install

set -o pipefail

REAL="${realPath}"
KASBAH_API="\${KASBAH_API_URL:-${apiUrl}}"
HTTPS_PROXY="\${HTTPS_PROXY:-${proxyUrl}}"
HTTP_PROXY="\${HTTP_PROXY:-${proxyUrl}}"
export HTTPS_PROXY HTTP_PROXY

# Record invocation (fire-and-forget — never block the user's command)
(
  curl -s -m 0.3 -X POST "\$KASBAH_API/v1/shim/record" \\
    -H "content-type: application/json" \\
    -d "{\\"bin\\":\\"${binName}\\",\\"args\\":\\"\$*\\",\\"cwd\\":\\"\$PWD\\",\\"ppid\\":\$PPID,\\"ts\\":\$(date +%s%N | cut -c1-13)}" \\
    >/dev/null 2>&1
) &

# Pre-flight: govern the prompt arg through Kasbah (3s timeout) with local
# regex fallback so we still block known patterns even if the API is cold/slow.
PROMPT_TEXT="\$*"
JAILBREAK_REGEX='(ignore (all|previous) (instructions|prompts)|disregard.*(instructions|prompt)|you are (now )?DAN|do anything now|reveal.*(system prompt|hidden|secret|password)|jailbroken?)'
if [ \${#PROMPT_TEXT} -gt 20 ] && [ \${#PROMPT_TEXT} -lt 4000 ]; then
  # Local fast-path: regex match → block immediately
  if echo "\$PROMPT_TEXT" | grep -iqE "\$JAILBREAK_REGEX"; then
    printf '\\n\\033[1;31m⛔ Kasbah blocked this ${binName} call\\033[0m\\n' >&2
    printf '   Pattern matched: known prompt-injection / jailbreak phrasing.\\n' >&2
    printf '   To override: KASBAH_BYPASS=1 ${binName} ...\\n\\n' >&2
    [ -n "\$KASBAH_BYPASS" ] || exit 137
  fi
  # API path: ask Kasbah for a proper verdict (3s timeout, fail-open on error)
  VERDICT=\$(curl -s -m 3 -X POST "\$KASBAH_API/v1/govern" \\
    -H "content-type: application/json" \\
    -d "{\\"prompt\\":\\"\${PROMPT_TEXT//\\"/\\\\\\"}\\",\\"context\\":\\"cli-shim:${binName}\\"}" 2>/dev/null \\
    | sed -n 's/.*"verdict":"\\([A-Z]*\\)".*/\\1/p')
  if [ "\$VERDICT" = "DENY" ]; then
    printf '\\n\\033[1;31m⛔ Kasbah blocked this ${binName} call\\033[0m\\n' >&2
    printf '   Prompt flagged by pre-flight governance.\\n' >&2
    printf '   Audit: curl http://127.0.0.1:8788/v1/audit | jq .audit[0]\\n\\n' >&2
    [ -n "\$KASBAH_BYPASS" ] || exit 137
  fi
fi

# Exec the real binary (replaces this shell — clean exit codes, signals)
exec "\$REAL" "\$@"
`;

// In-memory log of recent invocations (also persisted to JSONL)
const recentInvocations = [];

function ensureDirs() {
  fs.mkdirSync(SHIM_DIR, { recursive: true });
  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });
}

function findRealBinary(binName) {
  // We need the REAL binary path, not our shim. Search PATH excluding our shim dir.
  const PATH = (process.env.PATH || '').split(':').filter(p => p !== SHIM_DIR && p);
  for (const dir of PATH) {
    const p = path.join(dir, binName);
    try {
      const st = fs.statSync(p);
      if (st.isFile() && (st.mode & 0o111)) return p;
    } catch (_) {}
  }
  return null;
}

function installAllShims(apiUrl, proxyUrl) {
  ensureDirs();
  const results = [];
  for (const cli of AI_CLI_CATALOG) {
    const real = findRealBinary(cli.bin);
    if (!real) { results.push({ bin: cli.bin, status: 'not-installed', label: cli.label }); continue; }
    const shimPath = path.join(SHIM_DIR, cli.bin);
    try {
      fs.writeFileSync(shimPath, SHIM_TEMPLATE(cli.bin, real, apiUrl, proxyUrl));
      fs.chmodSync(shimPath, 0o755);
      results.push({ bin: cli.bin, status: 'installed', shimPath, realPath: real, label: cli.label, kind: cli.kind });
    } catch (e) {
      results.push({ bin: cli.bin, status: 'error', error: e.message, label: cli.label });
    }
  }
  return results;
}

function uninstallAllShims() {
  if (!fs.existsSync(SHIM_DIR)) return { removed: 0 };
  let n = 0;
  for (const f of fs.readdirSync(SHIM_DIR)) {
    try { fs.unlinkSync(path.join(SHIM_DIR, f)); n++; } catch(_) {}
  }
  return { removed: n };
}

function listShims() {
  if (!fs.existsSync(SHIM_DIR)) return [];
  return fs.readdirSync(SHIM_DIR).map(name => {
    const p = path.join(SHIM_DIR, name);
    let target = null;
    try {
      const content = fs.readFileSync(p, 'utf8');
      const m = content.match(/^REAL="([^"]+)"/m);
      if (m) target = m[1];
    } catch (_) {}
    const meta = AI_CLI_CATALOG.find(c => c.bin === name);
    return { bin: name, target, label: meta?.label, kind: meta?.kind };
  });
}

// ─── Mount ───────────────────────────────────────────────────────────────────
function mount(app) {
  app.get('/v1/shim/init', (_req, res) => {
    res.type('text/plain').send([
      `# Kasbah CLI shim init — eval "$(curl -s http://127.0.0.1:8788/v1/shim/init)"`,
      `export PATH="${SHIM_DIR}:$PATH"`,
      `export KASBAH_API_URL="http://127.0.0.1:${process.env.PORT || 8788}"`,
      `export HTTPS_PROXY="http://127.0.0.1:${process.env.KASBAH_PROXY_PORT || 8789}"`,
      `export HTTP_PROXY="$HTTPS_PROXY"`,
      `# Kasbah CLI shims active. Every AI CLI on PATH is now governed.`,
    ].join('\n'));
  });

  app.get('/v1/shim/list', (_req, res) => {
    res.json({
      shimDir: SHIM_DIR,
      shims:   listShims(),
      catalog: AI_CLI_CATALOG.length,
    });
  });

  app.post('/v1/shim/install', (req, res) => {
    const apiUrl   = (req.body && req.body.apiUrl)   || `http://127.0.0.1:${process.env.PORT || 8788}`;
    const proxyUrl = (req.body && req.body.proxyUrl) || `http://127.0.0.1:${process.env.KASBAH_PROXY_PORT || 8789}`;
    const results = installAllShims(apiUrl, proxyUrl);
    const installed = results.filter(r => r.status === 'installed');
    res.json({
      ok: true,
      shimDir: SHIM_DIR,
      installed: installed.length,
      notInstalled: results.filter(r => r.status === 'not-installed').length,
      errors: results.filter(r => r.status === 'error').length,
      results,
      shellSnippet: `export PATH="${SHIM_DIR}:$PATH"`,
      next: 'Add the above line to ~/.zshrc or run: eval "$(curl -s http://127.0.0.1:8788/v1/shim/init)"',
    });
  });

  app.post('/v1/shim/uninstall', (_req, res) => res.json(uninstallAllShims()));

  app.get('/v1/shim/recent', (_req, res) => res.json({ recent: recentInvocations.slice(0, 50) }));

  // The shim itself POSTs here — fire-and-forget logging
  app.post('/v1/shim/record', (req, res) => {
    const entry = { ts: Date.now(), ...(req.body || {}) };
    recentInvocations.unshift(entry);
    if (recentInvocations.length > 200) recentInvocations.length = 200;
    try { fs.appendFileSync(LOG_FILE, JSON.stringify(entry) + '\n'); } catch (_) {}
    res.json({ ok: true });
  });

  console.log(`[cli-shim] mounted — ${AI_CLI_CATALOG.length} CLIs in catalog · shim dir: ${SHIM_DIR}`);
}

module.exports = { mount, installAllShims, listShims, AI_CLI_CATALOG, SHIM_DIR };
