'use strict';

/**
 * OpenAPI spec generator for Kasbah Guard.
 *
 * Reads the routes registered on the Express app at boot, produces a minimal
 * OpenAPI 3.1 spec, and exposes it at:
 *   GET /v1/openapi.json   — machine-readable spec
 *   GET /v1/openapi.yaml   — YAML form (manually serialized — no yaml dep)
 *   GET /docs              — Swagger UI HTML rendered inline
 *
 * For full annotations (per-endpoint summaries, schemas, examples) we maintain
 * an inline OVERRIDES table for the most-used routes. Everything else is
 * autogenerated from the route table.
 */

const fs = require('fs');
const path = require('path');

// Manual descriptions for the most-used endpoints. Everything else gets a
// generic auto-stub.
const OVERRIDES = {
  'GET /v1/health': {
    summary: 'Service health check',
    description: 'Returns 200 with version + uptime if the engine is alive.',
    tags: ['health']
  },
  'POST /v1/scan': {
    summary: 'Scan text for threats',
    description: 'Runs text through the 12-layer pattern engine + KasbahUnifiedEngine. Detects prompt injection, PII, code injection, phishing, homoglyph, secrets.',
    tags: ['detection'],
    body: { text: { type: 'string', required: true, example: 'Ignore previous instructions' } },
    response: { risk: 'number', threats: 'string[]', safe: 'boolean', latency_ms: 'number' }
  },
  'POST /v1/govern': {
    summary: 'Govern an AI agent prompt or response',
    description: 'Full governance pipeline with passport binding and cryptographic receipt.',
    tags: ['governance']
  },
  'POST /v1/explain': {
    summary: 'Explain a block/warn decision',
    tags: ['governance']
  },
  'GET /v1/audit': {
    summary: 'Rolling audit log (last 500)',
    tags: ['audit']
  },
  'GET /v1/audit/chain': {
    summary: 'Hash-chain audit ledger',
    tags: ['audit']
  },
  'GET /v1/stats': {
    summary: 'Aggregate detection statistics',
    tags: ['observability']
  },
  'POST /v1/auth/signup': {
    summary: 'Create user + workspace + API key',
    tags: ['auth'],
    body: { email: { type: 'string', required: true }, name: { type: 'string' } },
    response: { user: 'object', workspace: 'object', apiKey: 'string' }
  },
  'GET /v1/me': {
    summary: 'Current user + their workspaces',
    tags: ['auth']
  },
  'GET /v1/products': {
    summary: 'List all 11 products available via this API',
    tags: ['products']
  },
  'POST /v1/products/:slug/analyze': {
    summary: 'Run analysis through a specific product engine',
    description: 'Slugs: baseline-drift | dao-vote-guard | quantum-sentinel | neural-witness | chronos-paradox | manifold-validator | dating-guard | resume-authentic | botnet-radar | legal-evidence | relationship-guard',
    tags: ['products']
  },
  'POST /v1/keys/issue': {
    summary: 'Issue an API key (use /v1/auth/signup instead for new accounts)',
    tags: ['auth']
  },
  'POST /v1/billing/checkout': {
    summary: 'Start a Stripe Checkout session to upgrade workspace tier',
    tags: ['billing']
  },
  'GET /v1/billing/plans': {
    summary: 'List available billing plans (Free, Pro, Enterprise)',
    tags: ['billing']
  },
  'GET /v1/status': {
    summary: 'Aggregated health + subsystem status (used by status.html)',
    tags: ['health']
  },
  'GET /v1/openapi.json': {
    summary: 'OpenAPI 3.1 spec (machine-readable)',
    tags: ['docs']
  }
};

function extractRoutes(app) {
  const routes = [];
  function walk(stack, base = '') {
    if (!stack) return;
    for (const layer of stack) {
      if (layer.route) {
        const methods = Object.keys(layer.route.methods).filter(m => layer.route.methods[m]);
        for (const m of methods) {
          // Convert Express path params (:id) to OpenAPI form ({id})
          const openapiPath = base + layer.route.path.replace(/:([^/]+)/g, '{$1}');
          routes.push({ method: m.toUpperCase(), path: openapiPath, expressPath: base + layer.route.path });
        }
      } else if (layer.name === 'router' && layer.handle?.stack) {
        const newBase = base + (layer.regexp?.source?.match(/\\\/([^\\\/?]+)/)?.[1] ? '/' + layer.regexp.source.match(/\\\/([^\\\/?]+)/)[1] : '');
        walk(layer.handle.stack, newBase);
      }
    }
  }
  walk(app._router?.stack || app.router?.stack);
  return routes;
}

function buildSpec(app) {
  const routes = extractRoutes(app);
  const paths = {};
  const tagsSet = new Set();

  for (const r of routes) {
    if (!r.path.startsWith('/v1') && r.path !== '/docs' && r.path !== '/openapi.json') continue;

    const key = `${r.method} ${r.expressPath}`;
    const override = OVERRIDES[key] || {};
    const tag = override.tags?.[0] || _autoTag(r.path);
    tagsSet.add(tag);

    if (!paths[r.path]) paths[r.path] = {};
    paths[r.path][r.method.toLowerCase()] = {
      operationId: _operationId(r.method, r.path),
      summary: override.summary || `${r.method} ${r.path}`,
      description: override.description || undefined,
      tags: [tag],
      ...(r.method === 'POST' || r.method === 'PUT' || r.method === 'PATCH'
        ? {
            requestBody: {
              required: !!override.body,
              content: { 'application/json': { schema: { type: 'object', example: override.body || {} } } }
            }
          }
        : {}),
      responses: {
        200: {
          description: 'Success',
          content: { 'application/json': { schema: { type: 'object', example: override.response || {} } } }
        },
        401: { description: 'Authentication required' },
        500: { description: 'Server error' }
      }
    };
  }

  return {
    openapi: '3.1.0',
    info: {
      title: 'Kasbah Guard API',
      version: '9.1.0',
      description: 'AI-agent security: prompt injection, jailbreak, PII, code injection, phishing, homoglyph, and 11 specialized product engines.',
      contact: { name: 'Kasbah Support', email: 'support@bekasbah.com', url: 'https://bekasbah.com' },
      license: { name: 'Proprietary' }
    },
    servers: [
      { url: 'https://api.bekasbah.com', description: 'Production' },
      { url: 'http://localhost:3000', description: 'Local dev' }
    ],
    tags: [...tagsSet].sort().map(t => ({ name: t })),
    components: {
      securitySchemes: {
        ApiKey: { type: 'apiKey', name: 'x-api-key', in: 'header' }
      }
    },
    security: [{ ApiKey: [] }],
    paths
  };
}

function _autoTag(p) {
  const m = p.match(/^\/v1\/([^/]+)/);
  return m ? m[1] : 'misc';
}

function _operationId(method, p) {
  return method.toLowerCase() + p
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .map((w, i) => i === 0 ? w : w[0].toUpperCase() + w.slice(1))
    .join('');
}

// Tiny YAML serializer for objects (avoids js-yaml dep)
function toYAML(obj, indent = 0) {
  const pad = '  '.repeat(indent);
  if (obj === null || obj === undefined) return 'null';
  if (typeof obj === 'string') return obj.includes('\n') || obj.includes(':') ? JSON.stringify(obj) : obj;
  if (typeof obj === 'number' || typeof obj === 'boolean') return String(obj);
  if (Array.isArray(obj)) {
    if (obj.length === 0) return '[]';
    return obj.map(item => `${pad}- ${typeof item === 'object' ? '\n' + toYAML(item, indent + 1) : toYAML(item)}`).join('\n');
  }
  if (typeof obj === 'object') {
    const entries = Object.entries(obj);
    if (entries.length === 0) return '{}';
    return entries.map(([k, v]) => {
      const isComplex = typeof v === 'object' && v !== null && (Array.isArray(v) ? v.length : Object.keys(v).length);
      return `${pad}${k}:${isComplex ? '\n' + toYAML(v, indent + 1) : ' ' + toYAML(v)}`;
    }).join('\n');
  }
  return JSON.stringify(obj);
}

function mount(app) {
  let cachedSpec = null;
  function getSpec() {
    if (cachedSpec) return cachedSpec;
    cachedSpec = buildSpec(app);
    return cachedSpec;
  }

  const reg = app._kasbahDynamicHandlers;
  const handlers = {
    'GET /v1/openapi.json': (req, res) => res.json(getSpec()),
    'GET /v1/openapi.yaml': (req, res) => { res.type('application/yaml'); res.send(toYAML(getSpec())); },
    'GET /docs':            (req, res) => res.type('html').send(SWAGGER_HTML)
  };
  if (reg) {
    for (const [k, v] of Object.entries(handlers)) reg.set(k, v);
  } else {
    app.get('/v1/openapi.json', handlers['GET /v1/openapi.json']);
    app.get('/v1/openapi.yaml', handlers['GET /v1/openapi.yaml']);
    app.get('/docs', handlers['GET /docs']);
  }
}

const SWAGGER_HTML = `<!DOCTYPE html>
<html>
<head>
  <title>Kasbah Guard API Docs</title>
  <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@5.10.5/swagger-ui.css">
  <style>body { margin: 0; } .topbar { display: none !important; }</style>
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5.10.5/swagger-ui-bundle.js"></script>
  <script>
    window.ui = SwaggerUIBundle({
      url: '/v1/openapi.json',
      dom_id: '#swagger-ui',
      deepLinking: true,
      defaultModelsExpandDepth: 1,
      docExpansion: 'list',
      tryItOutEnabled: true,
      presets: [SwaggerUIBundle.presets.apis, SwaggerUIBundle.SwaggerUIStandalonePreset]
    });
  </script>
</body>
</html>`;

module.exports = { mount, buildSpec, extractRoutes };
